### ISSUE TITLE
Made it into a package

### ISSUE THREAD

**Issue by b-rodrigues** [gerkovink/parlMICE#5]
Hi,

I took the liberty to put the function into a package that you can find here: https://github.com/b-rodrigues/parlMICE

I credit you as the original author. Would you be interested in turning `parlMice` into a proper package? I could help. What I did here is pretty barebones.

**Comment by gerkovink** [comment]
`parlmice` is now in `mice` in a hugely updated form. See stefvanbuuren/mice#104.
